### ISSUE TITLE
Mac binary doesn't work

### ISSUE THREAD

**Issue by wringrose** [amotile/stable-diffusion-studio#1]
Hi - just FYI the Mac binary doesn't work.

Happy to test any additional packages you make.

**Comment by amotile** [comment]
Do you have AUTOMATIC1111 installed?
Do you get any message when you run it?

**Comment by autumnmotor** [comment]
Hi.
I don't know why you decided that mac binary doesn't work, but it worked on my M1Mac (OS Ventura).
At first, nothing happened when I double-clicked amotile-studio-macos on the GUI, and I thought, "Is this a bug?"
On the terminal, set the binary file executable,

>chmod +x ./amotile-studio-macos

If I run AUTOMATIC1111 and run amotile-studio-macos binary

> run_webui_mac.sh
>./amotile-studio-macos

You can use it by accessing http://localhost:4000/

Translated by Google.
Thank you for reading my poor English.

**Comment by amotile** [comment]
Thank you for testing I will close this issue and keep including them in the release.
