### ISSUE TITLE
running on Colab

### ISSUE THREAD

**Issue by baristerzi** [amotile/stable-diffusion-studio#10]
Hi, can I run this code on Colab? Or how can I run it?

**Comment by amotile** [comment]
I don't think you can run my part of it on colab. 
But my code just offloads the heavy stuff to AUTOMATIC1111 and that one you can run of colab.
You would however need to either setup a proxy that points localhost:7860 to colab or change the code to point to the colab url (assuming that's possible, I haven't tried.)

**Comment by baristerzi** [comment]
Thanks,
There is no problem for AUTOMATIC111, we can run it easily in Colab. It's a good idea to try to run it on a common port. I will try. Maybe i will update this issue.
