### ISSUE TITLE
Bugs and notes

### ISSUE THREAD

**Issue by marianobastiUNRN** [amotile/stable-diffusion-studio#13]
Hi there, great work!

I've come across a couple of errors that wont let me test further;
1- It took me a while to figure out that A1111's webui had to be running in order to be able to run the compiled binaries (maybe add it to the README? )
2- When generating images, it's not clear what button does what, a description of what a button does when hovering with the mouse would be really useful!
**3-** I got an error when generating images, seems to be a UI error because the generation runs fine until it has to fetch the image, heres the console output:
![image](https://user-images.githubusercontent.com/113551508/197002641-3d36d1c0-4c64-41d4-b252-a7a4def87d81.png)

Would love to keep testing your interface!

**Comment by mischaschaub** [comment]
This is the same mistake I reported five days ago as issue11

**Comment by amotile** [comment]
I haven't had much time this week but in the weekend I hope to update the project to make sure it works with the latest version. (I will also note down what version I test it against).

**Comment by amotile** [comment]
1. README updated
2. Not fixed: Created a new issue for it. #15 
3. Newest release should have solved this.
