### ISSUE TITLE
Insta Crash

### ISSUE THREAD

**Issue by ShadoWxShinigamI** [amotile/stable-diffusion-studio#16]
I'm not sure what im doing wrong, but when i try to run the exe file after placing the .py files in the scripts folder, the cmd window pops and closes in a second. Its almost an instant crash. Also, I am running the webui before launch.

**Comment by amotile** [comment]
If you open a `Command Prompt` and run it from there you should hopefully be able to see the error message

**Comment by ShadoWxShinigamI** [comment]
Loading AUTOMATIC1111 config from: http://localhost:7860/config
C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:99
                    for (i = 0; i < config.dependencies.length; i++) {
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'length')
    at C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:99:57
    at step (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:33:23)
    at Object.next (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:14:53)
    at fulfilled (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

That is my error

**Comment by amotile** [comment]
Does your webui frontend run on http://localhost:7860 ?
Do you have the latest version of AUTOMATIC?
If you go to that url: http://localhost:7860/config what do you get?

**Comment by ShadoWxShinigamI** [comment]
Yep, I have the latest Auto1111 build. And yes it does run on 7860 port, and going to that url gives me a bunch of text, that starts with the line, 
{"version":"3.5\n","mode":"blocks","dev_mode":false,"components":

**Comment by amotile** [comment]
Heres a .exe. that will store the config file it gets from that url if this error happens. Maybe that would give us some clues:

[amotile-studio-win.zip](https://github.com/amotile/stable-diffusion-studio/files/9842376/amotile-studio-win.zip)

**Comment by ShadoWxShinigamI** [comment]
Ok, just ran the exe file. got an error folder with a config.json file, opening it on notepad++ gives me:-

"detail": "Not authenticated"
[error.zip](https://github.com/amotile/stable-diffusion-studio/files/9842531/error.zip)

Maybe me having a login for the webui is the issue?

**Comment by ShadoWxShinigamI** [comment]
Yep, tried running the webui without a password. It works without any issues now. Thanks for the help. But is there anyway, i can use this with the gradio auth feature?

**Comment by amotile** [comment]
Great!
That's not possible at the moment, but I'll create an issue for that.
