### ISSUE TITLE
Cannot find data folder for generated output

### ISSUE THREAD

**Issue by mischaschaub** [amotile/stable-diffusion-studio#2]
Your superb program offers one last hurdle to my final pleasure of getting an output from it: Where is the data folder to be found, where the generated output is stored? I was using the exec for installation.

**Comment by amotile** [comment]
After you have pressed the collect button it should be here:
It should be here: <exe-location>/data/collected

The only reason I can think of is if there's some kind of permission issue. so maybe it would work if you start it as administrator?

![image](https://user-images.githubusercontent.com/114049283/195167894-b7c13f80-2238-43eb-af15-f5eb8edf5219.png)
![image](https://user-images.githubusercontent.com/114049283/195167993-c87cfdc6-8baf-4cf3-ace2-5adc13cb17ed.png)
![image](https://user-images.githubusercontent.com/114049283/195168025-a5b5ceb5-3bea-4971-aa3f-fba323e561a9.png)

**Comment by amotile** [comment]
In the next version I plan to at least show a popup telling you where it saved it.

**Comment by mischaschaub** [comment]
My mistake: I was searching for the data folder under stable-diffusion-backend, as I had found somewhere in the doc. Only now I found the data folder beside the amotile-studio-win exe in my downloads folder. Please excuse!
Your program is very exiting and satisfying. Some questions remain open, for instance why I see in the upper right corner a red "1", which was not there in the beginning? How can I force the program to create the in-betweens of prompts at the start and the end of a sequence? A last observation: The prompts of my first trials are still mysteriously showing up in fresh sequences.

**Comment by mischaschaub** [comment]
Just some minutes further on I have understood a ton. Your app is so incredibly funny to use, a pure pleasure. A real game changer, finally it gets possible to tell a story with this generative stuff. Will definitely deliver tomorrow some results.

**Comment by amotile** [comment]
The red 1 is that you had something fail to generate, you can click the "broom" to clear it.
To make it create the inbetweens you can press the number buttons in playback or All to generate all of them.
I don't understand the last thing about the prompts showing up again. If it still happens you can create a new issue.

Finally: thank you for the kind words. It's still a bit unpolished but I'm glad you find it useful.
