### ISSUE TITLE
+Windows version .exe starting and shutting down immediately, no messages or errors, automatic1111 installed

### ISSUE THREAD

**Issue by nulone** [amotile/stable-diffusion-studio#3]
Its a bit wierd because its was able to run before i restart automatic1111

**Comment by nulone** [comment]
Problem solved by deleting this string from .bat :
set COMMANDLINE_ARGS --gradio-auth

**Comment by DenkingOfficial** [comment]
Not working even with all flags disabled, it shuts down immediately
