### ISSUE TITLE
Feature request: Add "clear images" to playback

### ISSUE THREAD

**Issue by Petri3D** [amotile/stable-diffusion-studio#8]
Hi,

I am unable to get the image generation restart when I adjust the timeline (location of the keyframes).  It would be good to have a brute force button to flush the generated images from playback timeline. Of course, if the software recognizes which sections of the timeline are invalid due to keyframe changes and resumes image generation, that would be even better.

Keep up the good work!

**Comment by mischaschaub** [comment]
Strange, the software does this in my installation, I change a keyframe or I insert one and then the related in-betweens are erased automatically.

**Comment by Petri3D** [comment]
I think it sometimes erases the frames on some portions, but many times It does not invalidate them and does nothing.

I also tried to keyframe a diffrent cfg value on whole time duration, but that did not help either

**Comment by amotile** [comment]
I can't reproduce this. You're welcome reopen with more information like screenshots if it is still an issue.
