### ISSUE TITLE
problem error

### ISSUE THREAD

**Issue by angelbpineda** [amotile/stable-diffusion-studio#9]
![image](https://user-images.githubusercontent.com/22414614/195992942-b34699dc-1f87-4831-999b-bf2401687e97.png)

**Comment by wwydmanski** [comment]
I'm getting a similar one :/
```
Loading AUTOMATIC1111 config from: http://localhost:7860/config
/snapshot/stable-diffusion-backend/dist/process/implementations/automatic1111.js:122
                        throw Error("No img2img function found");
Error: No img2img function found
    at /snapshot/stable-diffusion-backend/dist/process/implementations/automatic1111.js:122:31
    at step (/snapshot/stable-diffusion-backend/dist/process/implementations/automatic1111.js:33:23)
    at Object.next (/snapshot/stable-diffusion-backend/dist/process/implementations/automatic1111.js:14:53)
    at fulfilled (/snapshot/stable-diffusion-backend/dist/process/implementations/automatic1111.js:5:58)
```

**Comment by Ladypoly** [comment]
I get the same error as angelbpineda

**Comment by amotile** [comment]
Probably, I haven't had much time this week but in the weekend I hope to update the project to make sure it works with the latest version. (I will also note down what version I test it against).

**Comment by Pipazoul** [comment]
> ![image](https://user-images.githubusercontent.com/22414614/195992942-b34699dc-1f87-4831-999b-bf2401687e97.png)

Thanks to @sungam94 there is a quick fix 
https://github.com/amotile/stable-diffusion-studio/issues/11#issuecomment-1286733458

**Comment by amotile** [comment]
Newest release should have solved this.

**Comment by dustyny** [comment]
The latest windows build R4 still throws the error "No img2img function found"

**Comment by Pipazoul** [comment]
> The latest windows build R4 still throws the error "No img2img function found"

Do you have the logs  ?
Have you launched AUTOMATIC11111 webui before launching the binary ? if yes wich version ?
